### ISSUE TITLE
Swift file not found.

### ISSUE THREAD

**Issue by mhmtkrgz** [pubnative/pubnative-hybid-ios-sdk#329]
My app is writeen with OBJC and i am trying to integrate Hybid iOS SDK.

I was able to build without any issue with Hybid versions before 2.16.0. 

With your swift update, i am not able to build my project. 

I attached the issue screenshot.

<img width="2068" alt="Screenshot 2023-02-15 at 15 11 27" src="https://user-images.githubusercontent.com/11959163/219034765-94b82985-76cb-401a-849f-1ee654cfcc96.png">

Thanks in advance.

**Comment by can-soykarafakili** [comment]
Hi @mhmtkrgz ,

In our [HyBid iOS Demo App for Standalone Format GitHub Repo](https://github.com/pubnative/hybid-ios-standalone-demo), we have an Objective - C Sample App, where we are not facing the issue you've described. I'd recommend to check it first. Maybe you can find something useful there? Otherwise, we'll need more information about your project setup _(Is it an app or a SDK?, How are you trying to access the HyBid? etc.)_ so that we can help you.

Thanks.

**Comment by mhmtkrgz** [comment]
Thank you for quick response.

- It is an SDK, static library project
- HyBid installed with cocoapods
- no other dependencies. 

I attached an example.

[HybidAdapterDemo.zip](https://github.com/pubnative/pubnative-hybid-ios-sdk/files/10744192/HybidAdapterDemo.zip)

Thanks,
Mehmet.

**Comment by can-soykarafakili** [comment]
Hi @mhmtkrgz ,

Thanks for the information that you've provided. We'll check and check out what's going on.

Talk to you soon,

Thanks.

**Comment by faresbh** [comment]
Hello @mhmtkrgz ,

Please have a look at the Project attached. It uses a similar integration approach. 
`HyBidAdapter` is the static library, and `ParentProj` is the project that will integrate the library. 
The main difference here that we integrate HyBid as dynamic framework in cocoapods in `ParentProj`, and gets consumed in `HyBidAdapter`.` HyBid SDK`, in this case, is visible because of the header search path.  
Note also that we had to add those imports to the static library: 
```
#import <HyBid.h>
#import <HyBid-Generated-Interace-Swift.h>
```

Let us know if that fix your integration issue. 

Thanks. 
Fares
[HyBidSampleProject.zip](https://github.com/pubnative/pubnative-hybid-ios-sdk/files/10766322/HyBidSampleProject.zip)

**Comment by mhmtkrgz** [comment]
Hi @faresbh , 

use_frameworks! solved but i used following lines: 

```
#if __has_include(<HyBid/HyBid-Swift.h>)
    #import <HyBid/HyBid-Swift.h>
#else
    #import "HyBid-Swift.h"
#endif
```

Instead of this:
`#import <HyBid-Generated-Interace-Swift.h>`

**Comment by faresbh** [comment]
That's even better. 
`use_frameworks!` is added to include HyBid as a dynamic framework. 
Glad that you solve it. I'll close the issue.
